[font]
size = 12.0

[font.normal]
family = "MesloLGS NF"

[window]
dynamic_padding = true
dimensions = { columns = 120, lines = 35 }
#decorations = "None"

[window.padding]
x = 15
y = 20

[general]
import = ["/home/anders/.config/alacritty/dracula.toml"]
